### ISSUE TITLE
TSP cost function

### ISSUE THREAD

**Issue by SoerenDt** [yining043/VRP-DACT#10]
Hello folks, first of all thanks for your work. I have a question/concern regarding your [`get_costs`](https://github.com/yining043/VRP-DACT/blob/e99d59a6ab405f7c9c9d10132ba78003f92f0758/problems/problem_tsp.py#L206) function, in which I don't clearly get the computation of the cost of the tour. `d1` makes perfect sense, but `d2` seems to be wrong, as it should be similar to `d1` (but having the tour from `d1` shifted by one position to the right). From that code (in both branches), I don't see how the results of ~8 for TSP100 are achieved, given that I believe that you don't compute the correct tour cost.

It would be great, if you could clarify this :)
Best regards

**Comment by yining043** [comment]
Hi, there, thanks for your interest.

Please note that in our implementation, the solution is stored in a linked list format. Here, if rec[i] = j, it means the node i is connected to node j, i.e., edge i-j is in the solution. For example, if edge 0-1, edge 1-5, edge 2-10 are in the solution, so we have rec[0]=1, rec[1]=5 and rec[2]=10. Kindly see https://github.com/yining043/VRP-DACT/blob/new_version/Play_with_DACT.ipynb for an example at the end for TSP.

**Comment by yining043** [comment]
![image](https://github.com/yining043/VRP-DACT/assets/64318410/a9cb680e-3beb-48ac-a63a-a535b989c1d0)

**Comment by SoerenDt** [comment]
Thank you very much for clarification, that helped a lot. :)

**Comment by yining043** [comment]
> Thank you very much for clarification, that helped a lot. :)

You are welcome! Also, welcome to explore our latest work: https://github.com/yining043/NeuOpt
