### ISSUE TITLE
Q: Details about Run time Comparison

### ISSUE THREAD

**Issue by lensory** [yining043/VRP-DACT#7]
Thanks for your novel idea and beautiful codes~
I'm a green hand currently doing literature review in this area and testing different solvers with the dataset given here. I found that solving instances of cvrp20 with LKH(3.0.7) is quite fast, i.e., 0.01s for each instance. However, the metric given in the paper "[Learning to iteratively solve routing problems with dual-aspect collaborative transformer](https://arxiv.org/abs/2110.02544)" is 1h, which is far away from my result. 
Could you please give more detail about your work in the part Experiments. Thanks a lot!

**Comment by yining043** [comment]
Hi, thanks for your interest.

I think most of the papers in this field including DACT followed [AM [Kool et al.]](https://arxiv.org/abs/1803.08475) to report the results of LKH, where the time measured the total needed time of LKH to solve all 10,000 instances.

We are running 10,000 iterations of LKH on each instance. I believe 0.01s is too fast and can you double check your results?

For example, you can try solving one instance of CVRP20 from R dataset using the following commend:
./run_CVRP R R-E021-04m 10000 1

**Comment by lensory** [comment]
Thanks for your reply.
Maybe I know the reason. My configuration of LKH is 1 run with default max_trials (number of nodes), which is different from your setting (10,000 runs). Thank you again!
